@startuml
'https://plantuml.com/class-diagram

package sample{

    class Player{
        hand:Hand
        --
        openHand():void
    }

    class Hand{
        cards:List<Card>
        --
        getHand():List<Card>
    }

    class Card{
        mark:Mark
        number:Number
        --

    }
}



@enduml