@startuml
'https://plantuml.com/sequence-diagram

skinparam defaultFontName Cica

package domain.showDown {

    class Dealer {
        -hand : Hand
        --
        +open() : Hand
    }

    class Player {
        -hand : Hand
        --
        +open() : Hand
    }

    class Hand {
        -cards : List<Card>
    }

    class Card {
        -number : Number
        -mark : Mark
    }

    class HoleCard{

    }

    Card --> HoleCard
    HoleCard "1"--"1" Dealer

    Hand "1" --o "1" Player
    Hand "1" --o "1" Dealer
    Card "1..." --o "1" Hand

    class Number {
        -value : int
    }

    enum Mark {
        SPADE
        DIAMOND
        CLOVER
        HEART
    }

    Mark "1" --o "1" Card
    Number "1" --o "1" Card

}
@enduml